# HTML to Data Schema Converter Configuration

# LLM Settings
llm:
  provider: openai
  table_analysis_model: gpt-3.5-turbo
  schema_generation_model: gpt-3.5-turbo-16k
  schema_refinement_model: gpt-3.5-turbo-16k
  temperature: 0

# HTML Reader Settings
html_reader:
  max_file_size_mb: 10
  sample_rows: 5
  table_detection:
    search_div_classes: true
    detect_implicit_tables: true

# Schema Generation
schema_generation:
  max_tokens: 2000
  output_formats:
    - text
    - json
    - yaml

# Schema Refinement
schema_refinement:
  max_tokens: 2000
  enable_feedback: true

# Kaggle Integration
kaggle:
  enabled: true
  download_path: "kaggle_data"

# Output Settings
output:
  default_format: text
  save_metrics: true